# Generated by Django 4.1.5 on 2023-01-29 15:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('news_paper', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscribedCatUsers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categ', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news_paper.category')),
                ('user_s', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='category',
            name='subscribers',
            field=models.ManyToManyField(null=True, through='news_paper.SubscribedCatUsers', to=settings.AUTH_USER_MODEL),
        ),
    ]
