# Generated by Django 4.1.5 on 2023-01-29 15:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('news_paper', '0002_subscribedcatusers_category_subscribers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='subscribers',
            field=models.ManyToManyField(through='news_paper.SubscribedCatUsers', to=settings.AUTH_USER_MODEL),
        ),
    ]
